# Faker
- 가상 데이터 생성

In [1]:
# !pip install faker

Collecting faker
  Downloading Faker-35.2.0-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: python-dateutil>=2.4 in /opt/anaconda3/envs/pystudy_env/lib/python3.12/site-packages (from faker) (2.9.0.post0)
Requirement already satisfied: typing-extensions in /opt/anaconda3/envs/pystudy_env/lib/python3.12/site-packages (from faker) (4.12.2)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/envs/pystudy_env/lib/python3.12/site-packages (from python-dateutil>=2.4->faker) (1.17.0)
Downloading Faker-35.2.0-py3-none-any.whl (1.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 20.8 MB/s eta 0:00:00
Installing collected packages: faker
Successfully installed faker-35.2.0

In [5]:
from faker import Faker

fake = Faker()

print(fake.name())
print(fake.first_name() + " " + fake.last_name())
print(fake.email())
print(fake.company())
print(fake.date_of_birth(minimum_age=19, maximum_age=90))
# fake.address()
# fake.text()
# fake.email()
# fake.phone_number()
# fake.date_of_birth(minimum_age=18, maximum_age=65)
# fake.job()
# fake.company()
# fake.url()
# fake.ipv4()
# fake.ipv6()
# fake.user_agent()
# fake.password()
# fake.credit_card_number()
# fake.credit_card_expire()
# fake.credit_card_security_code()
# fake.credit_card_full()
# fake.currency_code()
# fake.currency_name()
# fake.currency_symbol()
# fake.currency()
# fake.file_name()
# fake.file_path()
# fake.file_extension()
# fake.mime_type()

Jose Patterson
Connor Hill
gdixon@example.com
Marsh, Lutz and Hunt
1998-08-18

In [8]:
import pandas as pd
import random

fake = Faker()

def gen_customer(n = 1000):
    arr = []
    for _ in range(n):
        data = {
            "AGE": fake.random_int(min=18, max=90),
            "SUB_MONTHS": fake.random_int(min=1, max=120),
            "MONTHLY_PAYME?NT": round(random.uniform(10, 100), 2),
            "USAGE_FEQ": fake.random_int(min=1, max=30),
            "STFT": fake.random_int(min=1, max=5),
            "CHURN": fake.boolean(chance_of_getting_true=30)
        }
        arr.append(data)
    return pd.DataFrame(arr)

In [10]:
df = gen_customer(200000)
df

        AGE  SUB_MONTHS  MONTHLY_PAYME?NT  USAGE_FEQ  STFT  CHURN
0        45          36             51.49         30     3   True
1        79          92             80.89         29     1  False
2        24         104             83.68          3     4   True
3        33          47             74.37         16     5  False
4        30          40             95.17          1     4  False
...     ...         ...               ...        ...   ...    ...
199995   41          84             81.34          2     3   True
199996   67          29             56.58         27     5  False
199997   90         101             94.43          8     1  False
199998   41          82             69.66          9     3   True
199999   29          87             68.34         20     1   True

[200000 rows x 6 columns]

In [11]:
df.to_csv("customer.csv", index=False)